frontend:
  replicaCount: 1

  image:
    repository: 227493789664.dkr.ecr.us-east-1.amazonaws.com/expense-tracker-frontend
    tag: "sha-d414fb2"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: nginx
    host: app.alonshak.online
    path: /
    pathType: Prefix
    tlsEnabled: true
    clusterIssuer: letsencrypt-prod
    tlsSecretName: frontend-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
