postgres:
  # כדי שה-Service יישאר בשם "postgres" וה-backend לא יישבר
  fullnameOverride: postgres

  auth:
    database: expense_db

    # משתמשים ב-Secret שה-ExternalSecret שלך יוצר
    existingSecret: expense-tracker-db

    # אצלך המפתח הוא POSTGRES_PASSWORD
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD

  primary:
    persistence:
      enabled: true
      size: 5Gi

externalSecrets:
  enabled: true

  aws:
    region: us-east-1
    secretName: expense-tracker/staging/db

  targetK8sSecretName: expense-tracker-db

  operator:
    namespace: external-secrets
    serviceAccountName: external-secrets

  keys:
    DATABASE_USER: DATABASE_USER
    DATABASE_PASSWORD: DATABASE_PASSWORD
    POSTGRES_USER: POSTGRES_USER
    POSTGRES_PASSWORD: POSTGRES_PASSWORD